### ISSUE TITLE
Support for nCentral 12.2

### ISSUE THREAD

**Issue by Robby-Swartenbroekx** [N-able/AgentDeploymentPackage#1]
nCentral 12.2's agent drops support for Windows 2008 and Windows Vista.
The latest agent version that can be used with that OS is agent 12.1.0.1102
I've requested this file on support: [http://public.b-inside.be/NAble/WindowsAgentSetup_12.1.0.1102.exe](http://public.b-inside.be/NAble/WindowsAgentSetup_12.1.0.1102.exe). Can this be added as a legacy2 possibility?

**Comment by rad-ryanc** [comment]
This is a distinct possibility! We have a small handful of Server 2008 Devices currently running Agent 12.1.1.241 in our environment and aren't experiencing any significant issues from what I've seen, so I may include that version (or a later Agent Hotfix **before** 12.2) in a future Release of the Deployment Package. I have noticed that the trend with Solarwinds MSP Release Notes tends to declare deprecated features ahead of the actual support cutoff, as I remember reading such an announcement in recent notes myself and expecting things not to work.

No ETA on this feature as of yet, as I always like to do some additional testing before I package something up. I have at least one other edit in mind, so we may see this rolled up into a 5.0.2 Release as time avails. 😃

**Comment by Robby-Swartenbroekx** [comment]
I'm running a 12.2 version of nCentral and we do see with (the few) 2008 we run that this is an issue.
Or I update my script, or I update all GPO to not being applied to 2008 servers.

**Comment by rad-ryanc** [comment]
Thanks for confirming that! I believe I have a suitable Agent for this "Legacy 2" Option and will include it with the next Release!

**Comment by Robby-Swartenbroekx** [comment]
It seems to work back with more recent agents, So I'm guessing this was only an issue with specific servers of with specific agent versions. 12.3..0.650 is installing on Windows 2008, so you can remove this request.
