### ISSUE TITLE
Change needed now that AgentMaint service proper startup is Automatic (Delayed Start)

### ISSUE THREAD

**Issue by bkST88r** [N-able/AgentDeploymentPackage#3]
now that the Agent Maintenance service is Automatic (Delayed Start), the script is incorrectly 'repairing' that to be just Auto, causing unreliable agent behavior.

**Comment by rad-ryanc** [comment]
I have added this issue to the Release Tasks for 5.0.2, which is currently in Development.

**Comment by AngryProgrammerInside** [comment]
Agent service repair is now an optional parameter in the partner config file in 6.0.2
